name: validate-data
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "data/**"

jobs:
  rebuild:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rebuild
        run: |
          pip install -e .
          parser_bench.validate_dirs data
